# posX_m[m] posY_m[m] posZ_m[m] yaw_rad[rad] 
# velX_ms[m/s] velY_ms[m/s] velZ_ms[m/s] yaw_rs[rad/s] 
# TIME[s]
# offboardMode:
# 1 - relative position
# 2 - velocity

/**:
  ros__parameters:
    offboardMode: 2
    x:
    - 0.0
    - 3.0
    - -3.0
    - 0.0
    - -3.0
    - 3.0
    - 0.0
    y:
    - 3.0
    - -3.0
    - 0.0
    - -3.0
    - 3.0
    - 0.0
    - 0.0
    z:
    - -2.0
    - -3.0
    - 1.0
    - 0.0
    - 1.0
    - 1.0
    - 0.0
    yaw:
    - -0.5
    - 0.0
    - 0.5
    - 0.0
    - -0.5
    - 0.0
    - -0.5
    time_s:
    - 20.0
    - 10.0
    - 5.0
    - 5.0
    - 10.0
    - 5.0
    - 1.0
    use_sim_time: false